In [5]:
import pandas as pd

In [10]:
data = {
    "Name": ["  Ali", "Sara ", "JOHN", "Ali", "Riya", None],
    "Age": [20, 21, "22", 20, "unknown", 23],
    "City": ["Rajkot", " rajkot", "Mumbai", "Rajkot", None, "Delhi"],
    "Gender": ["Male", "female", "MALE", "Male", "F", "Female"],
    "Salary": [25000, 30000, None, 25000, 40000, 35000],
    "Empty_Column": [None, None, None, None, None, None]
}

df = pd.DataFrame(data)

df.head()

    Name      Age     City  Gender   Salary Empty_Column
0    Ali       20   Rajkot    Male  25000.0         None
1  Sara        21   rajkot  female  30000.0         None
2   JOHN       22   Mumbai    MALE      NaN         None
3    Ali       20   Rajkot    Male  25000.0         None
4   Riya  unknown      NaN       F  40000.0         None

In [12]:
#inspect the data
df.shape

(6, 6)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          5 non-null      str
 1   Age           6 non-null      object
 2   City          5 non-null      str
 3   Gender        6 non-null      str
 4   Salary        5 non-null      float64
 5   Empty_Column  0 non-null      object
dtypes: float64(1), object(2), str(3)
memory usage: 498.0+ bytes

**2.Handling Missing Values**

In [18]:
df.isnull()

    Name    Age   City  Gender  Salary  Empty_Column
0  False  False  False   False   False          True
1  False  False  False   False   False          True
2  False  False  False   False    True          True
3  False  False  False   False   False          True
4  False  False   True   False   False          True
5   True  False  False   False   False          True

In [19]:
df.isnull().sum()

Name            1
Age             0
City            1
Gender          0
Salary          1
Empty_Column    6
dtype: int64

**3. Fill missing values**

In [20]:
df["Name"] = df["Name"].fillna("Unknown")

df

      Name      Age     City  Gender   Salary Empty_Column
0      Ali       20   Rajkot    Male  25000.0         None
1    Sara        21   rajkot  female  30000.0         None
2     JOHN       22   Mumbai    MALE      NaN         None
3      Ali       20   Rajkot    Male  25000.0         None
4     Riya  unknown      NaN       F  40000.0         None
5  Unknown       23    Delhi  Female  35000.0         None

In [21]:
df["City"] = df["City"].fillna("Unknown")

df

      Name      Age     City  Gender   Salary Empty_Column
0      Ali       20   Rajkot    Male  25000.0         None
1    Sara        21   rajkot  female  30000.0         None
2     JOHN       22   Mumbai    MALE      NaN         None
3      Ali       20   Rajkot    Male  25000.0         None
4     Riya  unknown  Unknown       F  40000.0         None
5  Unknown       23    Delhi  Female  35000.0         None

In [22]:
df["Salary"] = df["Salary"].fillna(df["Salary"].median())

df

      Name      Age     City  Gender   Salary Empty_Column
0      Ali       20   Rajkot    Male  25000.0         None
1    Sara        21   rajkot  female  30000.0         None
2     JOHN       22   Mumbai    MALE  30000.0         None
3      Ali       20   Rajkot    Male  25000.0         None
4     Riya  unknown  Unknown       F  40000.0         None
5  Unknown       23    Delhi  Female  35000.0         None

**5. Fix mixed data types**

In [23]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

df

      Name   Age     City  Gender   Salary Empty_Column
0      Ali  20.0   Rajkot    Male  25000.0         None
1    Sara   21.0   rajkot  female  30000.0         None
2     JOHN  22.0   Mumbai    MALE  30000.0         None
3      Ali  20.0   Rajkot    Male  25000.0         None
4     Riya   NaN  Unknown       F  40000.0         None
5  Unknown  23.0    Delhi  Female  35000.0         None